      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Run markdown lint
        run: |
          npm install remark-cli remark-preset-lint-consistent
          npm remark . --use remark-preset-link-consistent --frail
